### ISSUE TITLE
Wiki - update supported parameters

### ISSUE THREAD

**Issue by victorypoint** [grundic/jamulus-docker#12]
Should we assume most or all supported command-line parameters as per https://github.com/corrados/jamulus/wiki/Command-Line-Options are supported in latest docker build (v3.5.11)? Wiki needs an update to include --mutestream, --norecord, --multithreading, etc and deprecate --history.

https://github.com/grundic/jamulus-docker#parameters

**Comment by grundic** [comment]
Yes, all the parameters are supported: it's the same application, just packed to a docker container :)
Updated wiki except `--mutestream` -- seems this is a client only parameter.
