### ISSUE TITLE
Docker image on Synology Nas - start server?

### ISSUE THREAD

**Issue by jjnxpct** [grundic/jamulus-docker#16]
Hi! I am quite new to docker and also Jamulus. I would like to setup a Jamulus docker on my NAS so I can run an Jamulus server on this NAS.

Here is what I did so far:

On my Synology NAS I installed the Docker 'application' that can manage docker containers on the NAS. I followed a tutorial to install a Handbrake container on my NAs to get a feel of how it works. That went great.

So next I downloaded the image for the Jamulus docker and created a container on the NAS. I does look like this worked and the container is running. But I don't know what to do next.  Is suppose I need to start the Jamulus server within the container. I do see a terminal windows in the details of the container, but I don't know how to use that...

Is there a way I set up the container to also start the jamulus server with some specific parameters when the container is launched? I can set 'Environment' variables in the docker container but I am not sure if I can add a start server command here?

I hope someone can point me in the right direction. Because I am using the NAS docker application it might work a bit different then when I am on a 'normal' server with access to the commandline.

**Comment by jjnxpct** [comment]
I figured it out. It seems I can add a start command when I create the container from the downloaded image. This can not be changed in the container after it has been created. At least, I think.. But that's no problem. I now know I can use the advanced settings -> command field to input the server start command. Something like '-s -p 22124 -w "Welcome!"'.

**Comment by Robert53844** [comment]
Same experience on my side starting with docker and Jamulus.
I did the same a week ago and the Jamulus docker images works great on my Synology. 
I added two containers to switch easily between a private and public Jamulus server.
I hope, grundic will update the image to the new jamulus release 3.7.0 some day.

**Comment by grundic** [comment]
Sorry, I've switched to http://sonobus.net, which seem to have better latency and functionality over all. Updated docker image to 3.7.0.

**Comment by Robert53844** [comment]
Thanks a lot for updating to 3.7.0, although you have switched to Sonobus!
Sonobus seems to be a very interesting P2P solution like Jamkazam - but as free software. 
It may run into the same performance problems for orchestras with 30-50 musicians. 
In plucked string orchestras we made good/acceptable experiences with Jamulus and well performing audio interfaces.

**Comment by grundic** [comment]
Oh, that's very interesting. We're only 3 people, located in +/- the same area, so for us P2P works better. 
I'll try to keep this repository up to date. Good luck with your sessions 👋

**Comment by Robert53844** [comment]
Hi Grigory,

 

your grundic/jamulus-docker image is still used by a lot of musicians, so you did a really great job with it. It helps a lot of people throughout all kind of genres, from classical music (my hobby) to rock & pop.

 

I’ve seen that there is already an open pull request to upgrade the docker image vom version 3.7.0 to 3.8.0. Do you have a possibility to accept/merge this pull request to a current version?

 

Kind regards,

Robert

 

Von: Grigory Chernyshev ***@***.***> 
Gesendet: Mittwoch, 24. März 2021 08:59
An: grundic/jamulus-docker ***@***.***>
Cc: Robert53844 ***@***.***>; Comment ***@***.***>
Betreff: Re: [grundic/jamulus-docker] Docker image on Synology Nas - start server? (#16)

 

Oh, that's very interesting. We're only 3 people, located in +/- the same area, so for us P2P works better.
I'll try to keep this repository up to date. Good luck with your sessions 👋
