### ISSUE TITLE
Running on azure container instance failed but container running

### ISSUE THREAD

**Issue by pfiene** [grundic/jamulus-docker#17]
Any experience on running this container on azure container instances?
The Deployment failed on creating or updating the container group twice and self repaied later.
The container is up an running, but the instance remains in failed state.
I have the impression i can connct with jamulus client

**Comment by grundic** [comment]
Haven't used Azure. But docker technology should not depend on cloud provider or platform. Try viewing the logs using `docker logs <container>`. Probably it would show you an error.
