### ISSUE TITLE
push to docker hub

### ISSUE THREAD

**Issue by RobMeerwijk** [grundic/jamulus-docker#21]
Hi, I have a question. I can see that you updated the image to 3.8.1 on Oct 31st. It is not available on docker registry yet. Does it need some action or just patience? 

Thanks,

Rob Meerwijk

**Comment by grundic** [comment]
I don't create tags manually anymore, since I rarely use Jamulus (we switched to Sonobus).
You can fetch `latest` and that should contain 3.8.1

**Comment by RobMeerwijk** [comment]
Hi Grigory,

Somehow, I don't get 3.8.1 from the repository. My image sticks at 3.8.0

***@***.***:~# docker pull grundic/jamulus:latest*/
latest: Pulling from grundic/jamulus
Digest: 
sha256:4d40fd202e5d2dc4e581e0068d571ae4ceff31bc1672dea3ab21846564a23d70
Status: /Image is up to date for grundic/jamulus:latest/
docker.io/grundic/jamulus:latest
***@***.***:~# docker ps
CONTAINER ID   IMAGE COMMAND                  CREATED        STATUS 
PORTS                                           NAMES
bc2174236423   grundic/jamulus:latest         "Jamulus -n -u 6 -s …" /4 
months ago/   Up 11 minutes   0.0.0.0:22124->22124/udp, 
:::22124->22124/udp   jamulus

***@***.***:~# *//*docker logs bc2174236423*/

...

Using "172.17.0.3" as external IP.
Recording state not initialised
  *** Jamulus, Version */3.8.0/*
  *** Internet Jam Session Software
  *** Released under the GNU General Public License (GPL)

Am I doing something wrong?

Regards,

Rob

Op 12-11-2021 om 15:11 schreef Grigory Chernyshev:

**Comment by grundic** [comment]
Hey Rob,

Apparently, Docker disabled automatic builds some time ago. I have to build it locally now.
I've pushed `3.8.1`, could you please verify?

**Comment by RobMeerwijk** [comment]
Hi Grigory,

Ok, that is a pity. I can see that you pushed 3.8.1. The tag /latest/ 
still points to 3.8.0 I believe.

Rob

Op 15-11-2021 om 19:48 schreef Grigory Chernyshev:

**Comment by RobMeerwijk** [comment]
Hi Gregory,

Maybe docker still supports automated builds, they just made it harder 
to apply. It is still available for pro users and for open source projects:

https://docs.docker.com/docker-hub/builds/

https://www.docker.com/community/open-source/application

Op 15-11-2021 om 19:48 schreef Grigory Chernyshev:

**Comment by grundic** [comment]
Ah, I haven't run docker for a while and forgot I have to push latest manually.

Thanks for heads up about Docker for open-source projects, it might help!

**Comment by RobMeerwijk** [comment]
Works now, thanks!

Op 16-11-2021 om 08:17 schreef Grigory Chernyshev:
