### ISSUE TITLE
Update to Jamulus 3.9.0

### ISSUE THREAD

**Issue by Robert53844** [grundic/jamulus-docker#25]
Jamulus 3.9.0 has been released a few days ago:
https://github.com/jamulussoftware/jamulus/releases

Would it be possible to update this docker container to the current version?

**Comment by grundic** [comment]
Hey @Robert53844, 

Thank you for letting me know. Yes, will do that asap.

**Comment by grundic** [comment]
Sorry for the delay, I was on vacation. The image is updated.

**Comment by Robert53844** [comment]
Thank you very much for the update. It's very kind of you - and I hope you could enjoy your vacation :-)

**Comment by TaylorRobinsonMusic** [comment]
Hi @Robert53844 ,
I'm curious if you've found any additional latency added from the extra networking layer that a dockerized version presents.

**Comment by Robert53844** [comment]
No, there are absolutely no latency problems. The docker container is running on a powerful NAS (Synology DS1621xs+) which is running with a 10 Gbit/s-connection in my home network and with an internet fiber connection with 1 GBit/s download and 500 Mbit/s upload connection.
