### ISSUE TITLE
Can't run detached

### ISSUE THREAD

**Issue by softins** [grundic/jamulus-docker#3]
Hi, great job on the packaging - thanks!

Problem I've found is that jamulus segfaults immediately on launch if `-d` is specified to detach the terminal, as per your example `docker` command. If I omit `-d`, it runs fine, but it outputs to the terminal.

**Comment by grundic** [comment]
Can you please specify full command line so I can try on my side?

**Comment by softins** [comment]
Don't worry about it. The problem was on 3.4.4 server. It doesn't occur on 3.4.7 server which detaches just fine. Thanks!
